name: grin
version: v5.0.4
summary: Minimal implementation of the Mimblewimble protocol
description: |
  https://grin.mw/

epoch: 3*
confinement: strict
grade: stable
base: core18
parts:
  grin:
    plugin: rust
    source: https://github.com/mimblewimble/grin.git
    source-tag: v5.0.4
    build-packages:
      - clang
      - libncurses5-dev
      - libncursesw5-dev

  wallet:
    plugin: rust
    source: https://github.com/mimblewimble/grin-wallet.git
    source-tag: v5.0.3
    build-packages:
      - clang
      - pkg-config
      - libssl-dev

  tor:
    source: https://dist.torproject.org/tor-0.4.5.6.tar.gz
    source-checksum: sha256/22cba3794fedd5fa87afc1e512c6ce2c21bc20b4e1c6f8079d832dc1e545e733
    source-type: tar
    plugin: autotools
    build-packages:
      - libssl-dev
      - zlib1g-dev
    after: [libevent]
  
  libevent:
    source: https://github.com/libevent/libevent/releases/download/release-2.1.12-stable/libevent-2.1.12-stable.tar.gz
    source-checksum: sha256/92e6de1be9ec176428fd2367677e61ceffc2ee1cb119035037a27d346b0403bb
    source-type: tar
    plugin: autotools

apps:
  grin:
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    command: bin/grin
    plugs: [network, network-bind]
  wallet:
    command: bin/grin-wallet
    plugs: [network, network-bind]
